name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and test
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
    - name: Show current version of Xcode
      run: xcodebuild -version
    - name: Create GoogleService-Info.plist
      run: |
        cat > GoogleService-Info.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>CLIENT_ID</key>
          <string>dummy_client_id</string>
          <key>REVERSED_CLIENT_ID</key>
          <string>dummy_reversed_client_id</string>
          <key>API_KEY</key>
          <string>dummy_api_key</string>
          <key>GCM_SENDER_ID</key>
          <string>dummy_sender_id</string>
          <key>PLIST_VERSION</key>
          <string>1</string>
          <key>BUNDLE_ID</key>
          <string>com.example.app</string>
          <key>PROJECT_ID</key>
          <string>dummy_project_id</string>
          <key>STORAGE_BUCKET</key>
          <string>dummy_storage_bucket</string>
          <key>IS_ADS_ENABLED</key>
          <false/>
          <key>IS_ANALYTICS_ENABLED</key>
          <false/>
          <key>IS_APPINVITE_ENABLED</key>
          <false/>
          <key>IS_GCM_ENABLED</key>
          <false/>
          <key>IS_SIGNIN_ENABLED</key>
          <false/>
        </dict>
        </plist>
        EOF
        
    - name: Run tests
      run: ./run_tests.sh
